const y = require('js-yaml');
const fs = require('fs');
const s = fs.readFileSync('src/content/es/adjectives/adjective-agreement.mdx', 'utf8');
const m = s.match(/^---\r?\n([\s\S]*?)\r?\n---/);
const d = y.load(m[1]);
const out = [];
out.push('KEYS: ' + Object.keys(d).join(', '));
out.push('typeof slug: ' + typeof d.slug + ' | value: [' + String(d.slug) + ']');
out.push('typeof updated: ' + typeof d.updated + ' | ' + String(d.updated));
out.push('---FRONTMATTER---');
out.push(m[1]);
fs.writeFileSync('diag.txt', out.join('\n'), 'utf8');
console.log('diag written');